### ISSUE TITLE
Wrong auto-indent

### ISSUE THREAD

**Issue by diegodan1893** [benanders/ST2-ComputerCraft-Package#1]
when you define a function like this:

```
table = {
   a = function()
      print("test")
   end
}
```

it will indent correctly but if you want to add more functions, when you write a "," just after the end, it will move to the right:

```
table = {
   a = function()
      print("test")
      end,
}
```

**Comment by theoriginalbit** [comment]
tested this after making #8 and it is no longer a problem, can be closed.
